AWSTemplateFormatVersion: '2010-09-09'
Description: Set SQS permissions with lambda stack
Parameters:
  bucketName:
    Description: aws-monocyte-alarming distrubtion bucket that contains the Lambda function zip file
    Type: String
  zipFile:
    Description: Name of the monocyte alarming distribution zip file inside the bucket
    Type: String
  config:
    Description: Config of the Monocyte Alarming
    Type: String
Resources:
  monocyteUpdateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Sid: ''
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - '*'
            Effect: Allow
            Resource:
            - '*'
          Version: '2012-10-17'
        PolicyName: monocyteUpdatePolicy
  monocyteAlarmingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: bucketName
        S3Key:
          Ref: zipFile
      Description:
          Ref: config
      Handler: permission_lambda.update_sqs_permissions
      Role:
        Fn::GetAtt:
        - monocyteUpdateRole
        - Arn
      Runtime: python2.7
      Timeout: 15
